import os, sys
sys.path.append(".")

from build_config import libpath, cpppath, libs, ccflags, cxx, ccflags_debug, ccflags_optimize
import subprocess as sp


AddOption("--enable-debug", action="store_true", dest="enable_debug", default=False)
AddOption("--old-release", action="store_true", dest="old_release", default=False)

if GetOption("old_release"):
    ccflags.append("-DUSE_ALTERA_SDK")
	
if GetOption("enable_debug"):
    ccflags.extend(ccflags_debug)
else:
    ccflags.extend(ccflags_optimize)

srcs = ["utils.cpp", "device.cpp", "kernel.cpp", "context.cpp", "queue.cpp", "../thirdparty/cnpy.cpp"]
target = ["opencl_api"]

env = Environment(CXX = cxx, CCFLAGS = ccflags, CPPPATH = cpppath, LIBPATH=libpath, LIBS=libs, ENV=os.environ)
env.StaticLibrary(target, srcs)
